### ISSUE TITLE
getExternalFilesDirs

### ISSUE THREAD

**Issue by totalretribution** [pylerSM/XInternalSD#12]
I was hoping this would allow plex to use a usb drive however It does not work.
I decompiled plex and it looks like it uses getExternalFilesDirs instead of getExternalStorageDirectory.

Could this be updated to support getExternalFilesDirs. Perhaps even by appending the XinternalSD custom path to the array that getExternalFilesDirs returns.

This was found in location com\plexapp\plex\utilities\al.class if anyone wants to decompile plex.

**Comment by totalretribution** [comment]
I decided to look into this myself and I added getExternalFilesDirs  #13. Sadly Plex still does not work but this may be useful for something else.

**Comment by pylerSM** [comment]
this API may return null, maybe your pull request needs to handle this thing.

I could merge it, looks well. And I am gonna to fix one thing hopefully this weekend and then I can push update.

**Comment by totalretribution** [comment]
I will add a check for null when I get some time this week.

**Comment by pylerSM** [comment]
Great
