### ISSUE TITLE
can deny access (r/w)?

### ISSUE THREAD

**Issue by MakkoTech** [pylerSM/XInternalSD#15]
I Setting custom path /sdcard/XInternalSD/ and Enable several apps, reboot, but these apps still (r/w) files to /sdcard/. can restrict access /sdcard/XInternalSD/ without ../ etc?

**Comment by laintin** [comment]
I have another problem, test app use [Environment.getExternalStorageDirectory()](https://github.com/stirante/Storeprefs/blob/master/app/src/main/java/com/stirante/storeprefs/utils/SimpleDatabase.java) get the internal path, on boot start the Storeprefs config file is correct to my custom path, after all program booted, the Storeprefs config file incorrect to system default path.

I look up the XInternalSD source, on `findAndHookMethod Environment.class, "getExternalStorageDirectory"` i guess the function hook is global, not in single app `lpparam.classLoader`.

Maybe this is unable to change.

**Comment by laintin** [comment]
I try to change app internal access gids… remove sdcard media r/w, and add isolated app gid then use XInternalSD custom setting path to /data/data/islatesd/ , but i failed to do this.

**Comment by pylerSM** [comment]
Which Android version?

**Comment by laintin** [comment]
Version 5.1.1
Xposed Version 80

**Comment by laintin** [comment]
But i written a test and Log.v storage path… i wasn't aware that is wrong. no need reboot, changes enable or not enable is immediate, don't really know why in Storeprefs and more examples for Wechat, Alipay, etc…

**Comment by laintin** [comment]
`
		XposedHelpers.findAndHookMethod(Environment.class, "getExternalStorageDirectory", getExternalStorageDirectoryHook);
		XposedHelpers.findAndHookMethod(Environment.class, "getExternalStoragePublicDirectory", String.class, getExternalStoragePublicDirectoryHook);
		
		if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
			XposedHelpers.findAndHookMethod(XposedHelpers.findClass("android.app.ContextImpl", lpparam.classLoader), "getExternalFilesDir", String.class, getExternalFilesDirHook);
			XposedHelpers.findAndHookMethod(XposedHelpers.findClass("android.app.ContextImpl", lpparam.classLoader), "getObbDir", getObbDirHook);
		}

		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
			XposedHelpers.findAndHookMethod(XposedHelpers.findClass("android.app.ContextImpl", lpparam.classLoader), "getExternalFilesDirs", String.class, getExternalFilesDirsHook);
		}
`


`
	public void changeDirsPath(MethodHookParam param) {
		File[] oldDirPaths = (File[]) param.getResult();
		ArrayList<File> newDirPaths = new ArrayList<File>();

		String customInternalSd = getCustomInternalSd();
		if (customInternalSd.isEmpty()) {
			return;
		}

		for (int i=0; i<oldDirPaths.length; ++i) {
			String newDir = oldDirPaths[i].getPath().replaceFirst(getInternalSd(), customInternalSd);
			File newDirPath = new File(newDir);

			if (!newDirPath.exists())
				newDirPath.mkdirs();

			newDirPaths.add(newDirPath);
		}

		File[] appendedDirPaths = newDirPaths.toArray(new File[newDirPaths.size()]);
		param.setResult(appendedDirPaths);
	}
`

I try to change source code, make right:
![photo_2016-03-03_22-59-06](https://cloud.githubusercontent.com/assets/3026595/13498120/8e700f7c-e193-11e5-9b69-95911fbea72c.jpg)

but, still not effective at some apps, example Wechat.
I don't know these apps how to use Android API get my external storage path..
