### ISSUE TITLE
NPE when loading PreferenceFragment

### ISSUE THREAD

**Issue by aviraxp** [pylerSM/XInternalSD#22]
07-21 09:51:06.937: E/AndroidRuntime(17714): FATAL EXCEPTION: main
07-21 09:51:06.937: E/AndroidRuntime(17714): Process: com.pyler.xinternalsd, PID: 17714
07-21 09:51:06.937: E/AndroidRuntime(17714): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pyler.xinternalsd/com.pyler.xinternalsd.Preferences}: android.view.InflateException: Binary XML file line #22: Error inflating class java.lang.reflect.Constructor
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2271)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2320)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.ActivityThread.access$800(ActivityThread.java:138)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.os.Handler.dispatchMessage(Handler.java:102)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.os.Looper.loop(Looper.java:136)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.ActivityThread.main(ActivityThread.java:5117)
07-21 09:51:06.937: E/AndroidRuntime(17714): at java.lang.reflect.Method.invokeNative(Native Method)
07-21 09:51:06.937: E/AndroidRuntime(17714): at java.lang.reflect.Method.invoke(Method.java:515)
07-21 09:51:06.937: E/AndroidRuntime(17714): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
07-21 09:51:06.937: E/AndroidRuntime(17714): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
07-21 09:51:06.937: E/AndroidRuntime(17714): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
07-21 09:51:06.937: E/AndroidRuntime(17714): at dalvik.system.NativeStart.main(Native Method)
07-21 09:51:06.937: E/AndroidRuntime(17714): Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class java.lang.reflect.Constructor
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.createItem(GenericInflater.java:397)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.inflate(GenericInflater.java:326)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.inflate(GenericInflater.java:263)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:320)
07-21 09:51:06.937: E/AndroidRuntime(17714): at com.pyler.xinternalsd.Preferences$Settings.onCreate(Preferences.java:46)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.Fragment.performCreate(Fragment.java:1685)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:872)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1075)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.BackStackRecord.run(BackStackRecord.java:684)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.Activity.performStart(Activity.java:5358)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2244)
07-21 09:51:06.937: E/AndroidRuntime(17714): ... 12 more
07-21 09:51:06.937: E/AndroidRuntime(17714): Caused by: java.lang.reflect.InvocationTargetException
07-21 09:51:06.937: E/AndroidRuntime(17714): at java.lang.reflect.Constructor.constructNative(Native Method)
07-21 09:51:06.937: E/AndroidRuntime(17714): at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.GenericInflater.createItem(GenericInflater.java:383)
07-21 09:51:06.937: E/AndroidRuntime(17714): ... 28 more
07-21 09:51:06.937: E/AndroidRuntime(17714): Caused by: java.lang.NullPointerException
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:212)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.Preference.(Preference.java:286)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.DialogPreference.(DialogPreference.java:69)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.DialogPreference.(DialogPreference.java:90)
07-21 09:51:06.937: E/AndroidRuntime(17714): at android.preference.MultiSelectListPreference.(MultiSelectListPreference.java:49)
07-21 09:51:06.937: E/AndroidRuntime(17714): ... 31 more

**Comment by pylerSM** [comment]
Device? Android version? Steps to reproduce?

**Comment by aviraxp** [comment]
Meizu MX4, Flyme 4.2 based on Android 4.4.4

immediately when I  open app

**Comment by pylerSM** [comment]
ROM bug it seems.

**Comment by aviraxp** [comment]
Yes, I agree with you. Maybe it‘s because Meizu has changed Preferencefragment too much.

**Comment by pylerSM** [comment]
Sadly yes
