### ISSUE TITLE
Scanned and found a malware

### ISSUE THREAD

**Issue by drxgxn** [pylerSM/XInternalSD#26]
Bro i was scanning my device with malwarebyte and found this "Trogan.Ransum.Jisut.AP"

I don't know much about coding and hope for an simple explanation.
Thank you.

**Comment by xbolva00** [comment]
It is a scam, of course. Source code is public, so look, there is nothing bad there. Remove your shitty malware detector.

Or you downloaded APK from unofficial source  (i.e. not Xposed repo)

**Comment by pylerSM** [comment]
It is a scam, of course. Source code is public, so look, there is nothing bad there. Remove your shitty malware detector.

Or you downloaded APK from unofficial source (i.e. not Xposed repo)

**Comment by drxgxn** [comment]
Ok bro if you say so, but "malwarebytes" is one of the trusted app and i downloaded the module from the xposed installer itself. You can check my mail with the screenshot i sent you.
I will not bother you again
Thank you
☺

**Comment by colonel-lp** [comment]
Here is an answer to your question from Malwarebytes forums.

https://forums.malwarebytes.com/topic/213147-xinternalsd/
