### ISSUE TITLE
国产软件好像很多都不行

### ISSUE THREAD

**Issue by sundys** [pylerSM/XInternalSD#9]
微信,易信,淘宝,支付宝,网易这些客户端都识别不了映射的路径.估计函数不一样,期待解决.

**Comment by pylerSM** [comment]
Please try to use English language :) Sadly, I don't know Chinese...

I "google translated" your bug description so I can answer something. Apps, you mentioned, probably not use Android API to get internal SD path (they may hardcode it to "/sdcard/" or use some other "hacky" way - this means I can do nothing on my side :(

**Comment by tweet** [comment]
@pylerSM  It will be better if the path /sdcard/Android/* not been redirect to custom path.

**Comment by pylerSM** [comment]
Why not? :)

**Comment by martynbm** [comment]
#git clone

**Comment by martynbm** [comment]
git init
